### ISSUE TITLE
Bundle funktioniert nicht bei WMS-Diensten

### ISSUE THREAD

**Issue by StefanMenze** [conterra/mapapps-popups-action-screenshot#1]
Bundle funktioniert nicht bei WMS-Diensten

**Comment by matthiasstein** [comment]
Dies ist kein Fehler dieses Bundles. Es ist aktuell nicht möglich eigene Actions in Popups von WMS-Layern zu verwenden. Diese Anforderung wurde in map.apps unter dem Issue MAPAPPS-5711 erfasst.
